// Data-access layer for the artefacts table.

import { getSupabaseServiceClient } from "@/lib/supabase";
import { DEFAULT_OWNER } from "@/lib/constants";
import type { AgentConfig } from "@/agents/types";
import type { Artefact } from "@/types/artefact";

/** Returns every artefact for a programme, most recently created first. */
export async function listArtefactsForProgramme(programmeId: string): Promise<Artefact[]> {
  const { data, error } = await getSupabaseServiceClient()
    .from("artefacts")
    .select("*")
    .eq("programme_id", programmeId)
    .order("created_at", { ascending: false });

  if (error) {
    throw new Error(`Failed to list artefacts: ${error.message}`);
  }

  return data as Artefact[];
}

/** Returns one artefact by id, or null if it doesn't exist. */
export async function getArtefact(id: string): Promise<Artefact | null> {
  const { data, error } = await getSupabaseServiceClient()
    .from("artefacts")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) {
    throw new Error(`Failed to fetch artefact ${id}: ${error.message}`);
  }

  return data as Artefact | null;
}

/**
 * Records an artefact's content from an agent conversation. If a row already
 * exists for this (programme, artefact name), it's updated in place with the
 * version bumped — reverting to 'draft' even if it was previously approved,
 * since new content means it needs review again. Universal fields (version,
 * date, programme name, owner, disclaimer) are merged in here, never trusted
 * from the model.
 */
export async function recordArtefactDraft(
  programmeId: string,
  programmeName: string,
  agent: AgentConfig,
  artefactName: string,
  rawContent: Record<string, unknown>
): Promise<Artefact> {
  const client = getSupabaseServiceClient();

  const { data: existing, error: lookupError } = await client
    .from("artefacts")
    .select("*")
    .eq("programme_id", programmeId)
    .eq("artefact_name", artefactName)
    .maybeSingle();

  if (lookupError) {
    throw new Error(`Failed to look up artefact "${artefactName}": ${lookupError.message}`);
  }

  const nextVersion = existing ? (existing.version as number) + 1 : 1;
  const envelope = {
    ...rawContent,
    version: nextVersion,
    date: new Date().toISOString().slice(0, 10),
    programmeName,
    owner: DEFAULT_OWNER,
    disclaimer:
      "This output was generated by AI and must be reviewed by a human before being relied upon.",
  };

  const row = {
    programme_id: programmeId,
    artefact_name: artefactName,
    phase: agent.phase,
    activity: agent.name,
    agent_name: agent.name,
    version: nextVersion,
    status: "draft" as const,
    content: envelope,
    approved_at: null,
    approved_by: null,
  };

  const { data, error } = existing
    ? await client.from("artefacts").update(row).eq("id", existing.id).select().single()
    : await client.from("artefacts").insert(row).select().single();

  if (error) {
    throw new Error(`Failed to record artefact "${artefactName}": ${error.message}`);
  }

  return data as Artefact;
}

/** Marks an artefact as approved by the (current, single-user) owner. */
export async function approveArtefact(id: string): Promise<Artefact> {
  const { data, error } = await getSupabaseServiceClient()
    .from("artefacts")
    .update({ status: "approved", approved_at: new Date().toISOString(), approved_by: DEFAULT_OWNER })
    .eq("id", id)
    .select()
    .single();

  if (error) {
    throw new Error(`Failed to approve artefact ${id}: ${error.message}`);
  }

  return data as Artefact;
}
