// Test-data helpers for E2E specs. Write directly to Supabase using the
// service role key — no Next.js API layer, no Claude, no auth headers.
//
// Do NOT import from @/ — this file runs in the Playwright process, not
// in Next.js, so the tsconfig path aliases are unavailable here.

import { createClient, type SupabaseClient } from "@supabase/supabase-js";

// playwright.config.ts already loads .env.local via dotenv before any tests run.
function getServiceClient(): SupabaseClient {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    throw new Error(
      "NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in .env.local"
    );
  }
  return createClient(url, key, { auth: { persistSession: false } });
}

// Prefix applied to every test programme name so they can be bulk-deleted.
const E2E_PREFIX = "[E2E]";

// Foundation artefacts hardcoded here to avoid importing from the registry.
// Keep in sync with CLAUDE.md's Modernising Legacy / Foundation section.
const FOUNDATION_ARTEFACTS: { agentName: string; artefactNames: string[] }[] = [
  {
    agentName: "scope-sprint",
    artefactNames: ["Programme Charter", "Pilot Shortlist", "Value Scorecard"],
  },
  {
    agentName: "estate-mapping",
    artefactNames: ["Modernisation Blueprint", "Delivery Compass"],
  },
  { agentName: "infrastructure-blueprint", artefactNames: ["Platform Readiness Report"] },
  { agentName: "knowledge-forge", artefactNames: ["Intelligence Fabric"] },
  { agentName: "backlog-architecture", artefactNames: ["Delivery Backlog"] },
  {
    agentName: "delivery-intelligence",
    artefactNames: ["Command Centre", "Signal Engine", "Quality Covenant"],
  },
  {
    agentName: "launch-readiness",
    artefactNames: ["Forge Charter", "Crew Blueprint", "Forge Compass"],
  },
];

export interface TestProgramme {
  id: string;
  name: string;
}

/** Creates a legacy programme in the foundation phase. */
export async function createTestProgramme(nameSuffix: string): Promise<TestProgramme> {
  const db = getServiceClient();
  const name = `${E2E_PREFIX} ${nameSuffix}`;

  const { data, error } = await db
    .from("programmes")
    .insert({
      name,
      client: null,
      persona: "legacy",
      active_phase: "foundation",
      regulatory_frameworks: [],
      notes: "",
    })
    .select()
    .single();

  if (error) throw new Error(`seed: createTestProgramme failed: ${error.message}`);
  return { id: data.id as string, name: data.name as string };
}

/** Seeds all 14 Foundation artefacts as approved so the phase gate is immediately clear. */
export async function seedFoundationArtefactsApproved(
  programmeId: string,
  approvedBy: string
): Promise<void> {
  const db = getServiceClient();
  const now = new Date().toISOString();

  const rows = FOUNDATION_ARTEFACTS.flatMap(({ agentName, artefactNames }) =>
    artefactNames.map((artefactName) => ({
      programme_id: programmeId,
      artefact_name: artefactName,
      phase: "foundation",
      activity: agentName,
      agent_name: agentName,
      version: 1,
      status: "approved",
      content: {
        summary: `[E2E test seed] ${artefactName}`,
        disclaimer:
          "This output was generated by AI and must be reviewed by a human before being relied upon.",
      },
      approved_at: now,
      approved_by: approvedBy,
    }))
  );

  const { error } = await db.from("artefacts").insert(rows);
  if (error) throw new Error(`seed: seedFoundationArtefactsApproved failed: ${error.message}`);
}

export interface TestAlert {
  id: string;
  agent_name: string;
  what: string;
}

/**
 * Seeds one active alert for a programme, bypassing the agent engine.
 * Returns the alert id so specs can look it up.
 */
export async function seedAlert(
  programmeId: string,
  agentName: string,
  what: string,
  whyMatters: string[],
  suggestedAction: string
): Promise<TestAlert> {
  const db = getServiceClient();

  const { data, error } = await db
    .from("agent_alerts")
    .insert({
      programme_id: programmeId,
      agent_name: agentName,
      what,
      why_matters: whyMatters,
      suggested_action: suggestedAction,
      status: "active",
    })
    .select()
    .single();

  if (error) throw new Error(`seed: seedAlert failed: ${error.message}`);
  return { id: data.id as string, agent_name: data.agent_name as string, what: data.what as string };
}

/**
 * Deletes every programme whose name starts with the E2E prefix, including
 * their artefacts, chat sessions, and alerts. Call in beforeAll and afterAll
 * to keep the shared database tidy across runs.
 */
export async function deleteTestProgrammes(): Promise<void> {
  const db = getServiceClient();

  const { data, error } = await db
    .from("programmes")
    .select("id")
    .like("name", `${E2E_PREFIX}%`);

  if (error) throw new Error(`seed: deleteTestProgrammes failed to list: ${error.message}`);
  if (!data || data.length === 0) return;

  const ids = data.map((p: { id: string }) => p.id);

  await db.from("agent_alerts").delete().in("programme_id", ids);
  await db.from("artefacts").delete().in("programme_id", ids);
  await db.from("chat_sessions").delete().in("programme_id", ids);
  await db.from("programmes").delete().in("id", ids);
}
